databaseType = "MySql"
id = "c3b982c0-dcd2-4fad-93d8-a3435cad8c18"
name = "Amusing"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.amusing]
url = "jdbc:mysql://localhost:3306"
schemas = [ "Amusing" ]
displayName = "Amusing"
